export const categories = [
  { id: 'all', label: 'Todo' },
  { id: 'cheeseburgers', label: 'Cheeseburgers' },
  { id: 'clasicas', label: 'Clásicas' },
  { id: 'perez', label: 'Las Pérez' },
  { id: 'gourmet', label: 'Gourmet' },
  { id: 'compartir', label: 'Picar' },
  { id: 'verde', label: 'Pérez Verde' },
  { id: 'postres', label: 'Postres' },
  { id: 'bebidas', label: 'Bebidas' },
  { id: 'tragos', label: 'Tragos' },
  { id: 'cervezas', label: 'Cervezas' },
]

export const standardAddons = {
  burgers: [
    { id: 'extra-cheddar', name: 'Extra Cheddar', price: 1200 },
    { id: 'extra-panceta', name: 'Extra Panceta', price: 1500 },
    { id: 'cebolla-caramelizada', name: 'Cebolla Caramelizada', price: 800 },
    { id: 'medallon-extra', name: 'Medallón Smash Extra', price: 3000 },
    { id: 'sin-cebolla', name: 'Sin Cebolla', price: 0, isRemoval: true },
    { id: 'sin-pepinillos', name: 'Sin Pepinillos', price: 0, isRemoval: true },
  ],
  papas: [
    { id: 'extra-cheddar-papas', name: 'Extra Salsa Cheddar', price: 1200 },
    { id: 'bacon-picado', name: 'Extra Panceta Picada', price: 1000 },
    { id: 'cebolla-verdeo', name: 'Cebolla de Verdeo', price: 600 },
  ],
  bebidas: [
    { id: 'hielo', name: 'Hielo Extra', price: 0 },
    { id: 'limon', name: 'Rodaja de Limón', price: 0 },
  ]
}

export const products = [
  // ---- CHEESEBURGERS ----
  {
    id: 'cheeseburger',
    category: 'cheeseburgers',
    name: 'Cheeseburger',
    description: 'Medallón de carne smash a la plancha, queso cheddar fundido y pan brioche tostado. Acompañada de papas fritas crocantes.',
    price: 9900,
    image: null,
  },
  {
    id: 'doble-cheeseburger',
    category: 'cheeseburgers',
    name: 'Doble Cheeseburger',
    description: 'Dos medallones de carne smash caramelizados, doble capa de cheddar derretido. La favorita de la casa.',
    price: 14900,
    image: null,
    badge: 'Popular',
  },
  {
    id: 'triple-cheeseburger',
    category: 'cheeseburgers',
    name: 'Triple Cheeseburger',
    description: 'Tres medallones de carne smash apilados con triple capa de cheddar. Una experiencia intensa para los más hambrientos.',
    price: 18900,
    image: null,
    badge: 'XL',
  },

  // ---- CLÁSICAS ----
  {
    id: 'clasica',
    category: 'clasicas',
    name: 'Clásica',
    description: 'Medallón de carne casero jugoso, salsa big Pérez secreta, lechuga crocante, tomate maduro y pepinos encurtidos artesanales.',
    price: 10900,
    image: null,
  },
  {
    id: 'completa',
    category: 'clasicas',
    name: 'Completa',
    description: 'Medallón casero con panceta crocante, cheddar fundido, cebolla caramelizada al punto perfecto y nuestra salsa big Pérez.',
    price: 13900,
    image: null,
  },
  {
    id: 'extra-cheddar',
    category: 'clasicas',
    name: 'Extra Cheddar Extra Panceta',
    description: 'Doble medallón casero con cuádruple queso cheddar, panceta crocante y cebolla caramelizada. Nuestro plato más elegido.',
    price: 18900,
    image: null,
    badge: 'Top seller',
  },
  {
    id: 'pollo-frito',
    category: 'clasicas',
    name: 'Pollo Frito Crocante',
    description: 'Medallón de pollo empanizado y frito hasta quedar dorado, con huevo pochado, mostaza dijón y vegetales frescos.',
    price: 13000,
    image: null,
  },

  // ---- LAS PÉREZ ----
  {
    id: 'la-gran-perez',
    category: 'perez',
    name: 'La Gran Pérez',
    description: 'Nuestra obra maestra: dos medallones caseros con cuádruple cheddar, cuádruple panceta, cebolla caramelizada y crispy con aderezo secreto Pérez-H.',
    price: 19900,
    image: '/images/products/la-gran-perez.png',
    badge: 'Premium',
  },
  {
    id: 'mar-de-cheddar',
    category: 'perez',
    name: 'Mar de Cheddar',
    description: 'Tres medallones bañados en mares de cheddar derretido con panceta y cebolla caramelizada. Pedí el topping extra de cheddar y panceta.',
    price: 22900,
    image: '/images/products/mar-de-cheddar.png',
    badge: 'Signature',
  },
  {
    id: 'lademete',
    category: 'perez',
    name: 'LADEMENTE',
    description: 'Doble medallón casero con doble panceta, doble cheddar, salsa big Pérez y vegetales frescos. Nuestra best seller absoluta.',
    price: 20900,
    image: null,
    badge: 'Más vendido',
  },
  {
    id: 'la-mantequita',
    category: 'perez',
    name: 'La Mantequita',
    description: 'Doble medallón envuelto en papel aluminio con cuádruple cheddar y manteca ahumada que se derrite lentamente sobre la carne.',
    price: 16900,
    image: '/images/products/la-mantequita.png',
    badge: 'Chef',
  },

  // ---- GOURMET ----
  {
    id: 'caramel-bacon',
    category: 'gourmet',
    name: 'Caramel Bacon',
    description: 'Doble medallón con cuádruple cheddar y panceta caramelizada al horno, envuelta en papel aluminio para conservar toda su jugosidad.',
    price: 16900,
    image: null,
  },
  {
    id: 'la-picante',
    category: 'gourmet',
    name: 'La Picante',
    description: 'Medallón premium con panceta crocante, doble cheddar, aros de cebolla empanizados y nuestra salsa picante de la casa.',
    price: 15900,
    image: null,
  },
  {
    id: 'hongos-salteados',
    category: 'gourmet',
    name: 'Hongos Salteados',
    description: 'Pan de campo artesanal con medallón premium, queso azul, champiñones salteados, cebolla caramelizada y salsa ranch cremosa.',
    price: 15900,
    image: null,
  },

  // ---- PICAR Y COMPARTIR ----
  {
    id: 'papas-fritas',
    category: 'compartir',
    name: 'Papas Fritas Naturales',
    description: 'Papas fritas cortadas artesanalmente, doradas y crocantes, con sal marina fina.',
    price: 7900,
    image: null,
  },
  {
    id: 'papas-cheddar-panceta',
    category: 'compartir',
    name: 'Papas con Cheddar y Panceta',
    description: 'Papas fritas naturales ba�adas en salsa cheddar artesanal y cubiertas con panceta crocante reci�n hecha.',
    price: 12500,
    image: '/images/products/papas-cheddar-bacon.png',
  },
  {
    id: 'tequenos',
    category: 'compartir',
    name: 'Tequeños',
    description: 'Tequeños crujientes rellenos de queso, servidos con salsa de ajo casera.',
    price: 10900,
    image: '/images/products/tequenos.png',
  },
  {
    id: 'triangulitos-muzza',
    category: 'compartir',
    name: 'Triangulitos de Muzza',
    description: 'Triangulitos de muzzarella rebozados y dorados, bañados en nuestra salsa barbacoa ahumada artesanal.',
    price: 15900,
    image: null,
    badge: 'Para compartir',
  },
  {
    id: 'nuggets-pollo',
    category: 'compartir',
    name: 'Nuggets de Pollo',
    description: 'Bocaditos de pollo jugosos empanizados hasta quedar dorados, con salsa a elección.',
    price: 10900,
    image: null,
  },
  {
    id: 'aros-cebolla',
    category: 'compartir',
    name: 'Aros de Cebolla',
    description: 'Aros de cebolla crocantes y dorados, servidos con dos salsas dip artesanales a elección.',
    price: 13900,
    image: null,
  },

  // ---- PEREZ VERDE ----
  {
    id: 'not-perez',
    category: 'verde',
    name: 'NOT Pérez',
    description: 'Medallón vegetal NOT COW jugoso, lechuga fresca, tomate maduro, pepinos encurtidos y mayonesa vegetal.',
    price: 19900,
    image: null,
  },
  {
    id: 'not-chicken',
    category: 'verde',
    name: 'NOT Chicken',
    description: 'Medallón vegetal NOT CHICKEN crujiente, cebolla caramelizada dulce, lechuga y tomate fresco.',
    price: 19900,
    image: null,
  },
  {
    id: 'vegetariana',
    category: 'verde',
    name: 'Vegetariana',
    description: 'Medallón artesanal de quinoa, lentejas y vegetales, con cheddar fundido, lechuga y tomate del huerto.',
    price: 11900,
    image: null,
  },
  {
    id: 'ensalada-cesar',
    category: 'verde',
    name: 'Ensalada César',
    description: 'Mix de verdes frescos, queso en hebras, croutones artesanales y aderezo Pérez-H cremoso con panceta ahumada.',
    price: 12900,
    image: null,
  },
  {
    id: 'sin-tacc',
    category: 'verde',
    name: 'Sin TACC',
    description: 'Medallón de carne casero en pan artesanal sin gluten, con lechuga, tomate y nuestros vegetales frescos.',
    price: 12900,
    image: null,
  },
  {
    id: 'sin-tacc-extra',
    category: 'verde',
    name: 'Sin TACC Extra Cheddar Extra Panceta',
    description: 'Medallón casero con doble cheddar, doble panceta crocante en pan artesanal sin gluten. Sabor sin compromisos.',
    price: 16900,
    image: null,
    badge: 'Sin TACC',
  },

  // ---- POSTRES ----
  {
    id: 'chocotorta',
    category: 'postres',
    name: 'Chocotorta',
    description: 'Nuestra chocotorta artesanal: capas de chocolate, dulce de leche y crema Philadelphia, con galletitas de chocolate suaves.',
    price: 5900,
    image: null,
  },
  {
    id: 'mousse-chocolate',
    category: 'postres',
    name: 'Mousse de Chocolate',
    description: 'Mousse de chocolate amargo artesanal, textura a�rea y sedosa, con el punto perfecto de dulzor.',
    price: 5900,
    image: null,
  },
  {
    id: 'lemon-pie',
    category: 'postres',
    name: 'Lemon Pie',
    description: 'Clásico lemon pie con base de galletita, relleno de limón cremoso y merengue italiano dorado al soplete.',
    price: 5900,
    image: null,
  },

  // ---- BEBIDAS ----
  {
    id: 'coca-cola',
    category: 'bebidas',
    name: 'Gaseosa Línea Coca',
    description: 'Coca Cola, Sprite o Fanta, servidas bien frías en vaso con hielo.',
    price: 3500,
    image: null,
  },
  {
    id: 'pepsi',
    category: 'bebidas',
    name: 'Gaseosa Línea Pepsi',
    description: 'Pepsi, 7Up o Mirinda, refrescantes y bien fr�as.',
    price: 3200,
    image: null,
  },
  {
    id: 'aguas-saborizadas',
    category: 'bebidas',
    name: 'Aguas Saborizadas',
    description: 'Agua saborizada natural, ligera y refrescante.',
    price: 3000,
    image: null,
  },
  {
    id: 'agua-mineral',
    category: 'bebidas',
    name: 'Agua Mineral',
    description: 'Agua mineral pura, con o sin gas, servida bien fr�a.',
    price: 3000,
    image: null,
  },
  {
    id: 'limonada',
    category: 'bebidas',
    name: 'Limonada Natural',
    description: 'Limonada natural reci�n exprimida, dulce y refrescante.',
    price: 2500,
    image: null,
  },

  // ---- TRAGOS ----
  {
    id: 'gin-tonic',
    category: 'tragos',
    name: 'Gin Tonic',
    description: 'Gin tonic clásico preparado con gin premium, tónica artesanal y rodaja de limón fresca.',
    price: 7500,
    image: null,
  },
  {
    id: 'campari',
    category: 'tragos',
    name: 'Campari con Naranja',
    description: 'Campari servido con jugo de naranja reci�n exprimido y hielo. Amargo y refrescante.',
    price: 7500,
    image: null,
  },
  {
    id: 'cerveza-artesanal',
    category: 'tragos',
    name: 'Cerveza Artesanal',
    description: 'Cerveza artesanal tirada de la casa, eleg� entre rubia o roja. Notas maltosas y arom�ticas.',
    price: 5500,
    image: null,
  },
  {
    id: 'ipa',
    category: 'tragos',
    name: 'IPA',
    description: 'IPA artesanal con notas cítricas y florales, amarga y aromática. Para los amantes del lúpulo.',
    price: 6900,
    image: null,
    badge: 'Premium',
  },

  // ---- CERVEZAS ----
  {
    id: 'heineken',
    category: 'cervezas',
    name: 'Heineken',
    description: 'Heineken, la clásica holandesa. Servida en lata o porrón, bien fría.',
    price: 5500,
    image: null,
  },
  {
    id: 'corona',
    category: 'cervezas',
    name: 'Corona',
    description: 'Corona, ligera y refrescante. Perfecta para acompañar cualquier plato.',
    price: 5500,
    image: null,
  },
  {
    id: 'stella',
    category: 'cervezas',
    name: 'Stella Artois',
    description: 'Stella Artois, la belga premium con sabor balanceado y final limpio.',
    price: 5500,
    image: null,
  },
  {
    id: 'strauss',
    category: 'cervezas',
    name: 'Strauss Sin TACC',
    description: 'Strauss Sin TACC, cerveza artesanal libre de gluten sin comprometer el sabor.',
    price: 5500,
    image: null,
    badge: 'Sin TACC',
  },
]

export function formatCurrency(value) {
  return new Intl.NumberFormat('es-AR', {
    style: 'currency',
    currency: 'ARS',
    maximumFractionDigits: 0,
  }).format(value)
}
