export const categories = [
  { id: 'all', label: 'Todo' },
  { id: 'cheeseburgers', label: 'Cheeseburgers' },
  { id: 'clasicas', label: 'Clásicas' },
  { id: 'perez', label: 'Las Pérez' },
  { id: 'gourmet', label: 'Gourmet' },
  { id: 'compartir', label: 'Picar' },
  { id: 'verde', label: 'Pérez Verde' },
  { id: 'postres', label: 'Postres' },
  { id: 'bebidas', label: 'Bebidas' },
  { id: 'tragos', label: 'Tragos' },
  { id: 'cervezas', label: 'Cervezas' },
]

export const standardAddons = {
  burgers: [
    { id: 'extra-cheddar', name: 'Extra Cheddar', price: 1200 },
    { id: 'extra-panceta', name: 'Extra Panceta', price: 1500 },
    { id: 'cebolla-caramelizada', name: 'Cebolla Caramelizada', price: 800 },
    { id: 'medallon-extra', name: 'Medallón Smash Extra', price: 3000 },
    { id: 'sin-cebolla', name: 'Sin Cebolla', price: 0, isRemoval: true },
    { id: 'sin-pepinillos', name: 'Sin Pepinillos', price: 0, isRemoval: true },
  ],
  papas: [
    { id: 'extra-cheddar-papas', name: 'Extra Salsa Cheddar', price: 1200 },
    { id: 'bacon-picado', name: 'Extra Panceta Picada', price: 1000 },
    { id: 'cebolla-verdeo', name: 'Cebolla de Verdeo', price: 600 },
  ],
  bebidas: [
    { id: 'hielo', name: 'Hielo Extra', price: 0 },
    { id: 'limon', name: 'Rodaja de Limón', price: 0 },
  ]
}

export const products = [
  // ---- CHEESEBURGERS ----
  {
    id: 'cheeseburger',
    category: 'cheeseburgers',
    name: 'Cheeseburger',
    description: 'Clásica cheeseburger americana. Con medallón de carne smash y queso cheddar. Vienen con papas!',
    price: 9900,
    image: null,
  },
  {
    id: 'doble-cheeseburger',
    category: 'cheeseburgers',
    name: 'Doble Cheeseburger',
    description: 'Doble medallón smash, doble cheddar. No defrauda nunca. Con papas!',
    price: 14900,
    image: null,
    badge: 'Popular',
  },
  {
    id: 'triple-cheeseburger',
    category: 'cheeseburgers',
    name: 'Triple Cheeseburger',
    description: 'Triple medallón smash, triple cheddar. Pedila simple, doble o triple. Con papas!',
    price: 18900,
    image: null,
    badge: 'XL',
  },

  // ---- CLÁSICAS ----
  {
    id: 'clasica',
    category: 'clasicas',
    name: 'Clásica',
    description: 'Un medallón de carne casero con salsa big Pérez, lechuga, tomate y pepinos caseros. Con papas!',
    price: 10900,
    image: null,
  },
  {
    id: 'completa',
    category: 'clasicas',
    name: 'Completa',
    description: 'Un medallón de carne casero con panceta, queso cheddar, salsa big Pérez, cebolla caramelizada, lechuga, tomate y pepinos. Con papas!',
    price: 13900,
    image: null,
  },
  {
    id: 'extra-cheddar',
    category: 'clasicas',
    name: 'Extra Cheddar Extra Panceta',
    description: 'Un medallón de carne casero con doble queso cheddar, doble porción de panceta, salsa big Pérez y cebolla caramelizada. Con papas!',
    price: 18900,
    image: null,
    badge: 'Top seller',
  },
  {
    id: 'pollo-frito',
    category: 'clasicas',
    name: 'Pollo Frito Crocante',
    description: 'Un medallón de pollo crocante con queso cheddar, lechuga, tomate, huevo y mostaza dijon. Con papas!',
    price: 13000,
    image: null,
  },

  // ---- LAS PÉREZ ----
  {
    id: 'la-gran-perez',
    category: 'perez',
    name: 'La Gran Pérez',
    description: 'Dos medallones de carne casero con cuádruple queso cheddar, cuádruple panceta, cebolla caramelizada, cebolla crispy y aderezo Pérez-H. Con papas!',
    price: 19900,
    image: '/images/products/la-gran-perez.png',
    badge: 'Premium',
  },
  {
    id: 'mar-de-cheddar',
    category: 'perez',
    name: 'Mar de Cheddar',
    description: 'Tres medallones cubiertos de tres capas de queso cheddar, panceta y cebolla caramelizada. Bañala vos en una catarata de cheddar y panceta topping! Con papas!',
    price: 22900,
    image: '/images/products/mar-de-cheddar.png',
    badge: 'Signature',
  },
  {
    id: 'lademete',
    category: 'perez',
    name: 'LADEMENTE',
    description: 'Doble medallón de carne casero con doble panceta, doble queso cheddar, salsa big Pérez, cebolla caramelizada, lechuga, tomate y pepinos. Con papas!',
    price: 20900,
    image: null,
    badge: 'Más vendido',
  },
  {
    id: 'la-mantequita',
    category: 'perez',
    name: 'La Mantequita',
    description: 'Doble medallón de carne casero con cuádruple queso cheddar y baño de manteca ahumada envuelta en papel aluminio. Con papas!',
    price: 16900,
    image: '/images/products/la-mantequita.png',
    badge: 'Chef',
  },

  // ---- GOURMET ----
  {
    id: 'caramel-bacon',
    category: 'gourmet',
    name: 'Caramel Bacon',
    description: 'Doble medallón de carne casero con cuádruple queso cheddar y panceta caramelizada envuelta en papel aluminio. Con papas!',
    price: 16900,
    image: null,
  },
  {
    id: 'la-picante',
    category: 'gourmet',
    name: 'La Picante',
    description: 'Medallón de carne premium, dos fetas de panceta, doble queso cheddar, aros de cebolla y salsa picante. Con papas!',
    price: 15900,
    image: null,
  },
  {
    id: 'hongos-salteados',
    category: 'gourmet',
    name: 'Hongos Salteados',
    description: 'Pan de campo, medallón de carne premium, queso azul, champiñones, cebolla caramelizada, rúcula, tomate y salsa RANCH. Con papas!',
    price: 15900,
    image: null,
  },

  // ---- PICAR Y COMPARTIR ----
  {
    id: 'papas-fritas',
    category: 'compartir',
    name: 'Papas Fritas Naturales',
    description: 'Porción de papas fritas naturales caseras! Un manjar!',
    price: 7900,
    image: null,
  },
  {
    id: 'papas-cheddar-panceta',
    category: 'compartir',
    name: 'Papas con Cheddar y Panceta',
    description: 'Papas fritas naturales con nuestra salsa especial de queso cheddar y cubierta de panceta crocante.',
    price: 12500,
    image: '/images/products/papas-cheddar-bacon.png',
  },
  {
    id: 'tequenos',
    category: 'compartir',
    name: 'Tequeños',
    description: 'Porción de tequeños con salsa de ajo.',
    price: 10900,
    image: '/images/products/tequenos.png',
  },
  {
    id: 'triangulitos-muzza',
    category: 'compartir',
    name: 'Triangulitos de Muzza',
    description: 'Triangulitos de muzzarella rebozados bañados en salsa de barbacoa casera!',
    price: 15900,
    image: null,
    badge: 'Para compartir',
  },
  {
    id: 'nuggets-pollo',
    category: 'compartir',
    name: 'Nuggets de Pollo',
    description: 'Bocaditos de pollo rebozado con salsa a elección!',
    price: 10900,
    image: null,
  },
  {
    id: 'aros-cebolla',
    category: 'compartir',
    name: 'Aros de Cebolla',
    description: 'Porción de aros de cebolla crocantes con dos dips de salsa a elección!',
    price: 13900,
    image: null,
  },

  // ---- PEREZ VERDE ----
  {
    id: 'not-perez',
    category: 'verde',
    name: 'NOT Pérez',
    description: 'Medallón NOT COW, lechuga, tomate, pepinos caseros y NOT MAYO. Con papas!',
    price: 19900,
    image: null,
  },
  {
    id: 'not-chicken',
    category: 'verde',
    name: 'NOT Chicken',
    description: 'Medallón NOT CHICKEN, cebolla caramelizada, lechuga y tomate. Con papas!',
    price: 19900,
    image: null,
  },
  {
    id: 'vegetariana',
    category: 'verde',
    name: 'Vegetariana',
    description: 'Medallón de quinoa, lentejas, puerro y zanahorias con queso cheddar, lechuga y tomate fresco. Con papas!',
    price: 11900,
    image: null,
  },
  {
    id: 'ensalada-cesar',
    category: 'verde',
    name: 'Ensalada César',
    description: 'Colchón de mix de verdes, triángulos de queso en hebras, croutones y aderezo Pérez-H de queso crema y panceta ahumada.',
    price: 12900,
    image: null,
  },
  {
    id: 'sin-tacc',
    category: 'verde',
    name: 'Sin TACC',
    description: 'Un medallón de carne casero, lechuga, tomate y pan artesanal SIN TACC. Con papas!',
    price: 12900,
    image: null,
  },
  {
    id: 'sin-tacc-extra',
    category: 'verde',
    name: 'Sin TACC Extra Cheddar Extra Panceta',
    description: 'Un medallón de carne casero, doble queso cheddar y doble panceta en pan artesanal sin tacc. Con papas!',
    price: 16900,
    image: null,
    badge: 'Sin TACC',
  },

  // ---- POSTRES ----
  {
    id: 'chocotorta',
    category: 'postres',
    name: 'Chocotorta',
    description: 'Nuestra chocotorta casera, cremosa e irresistible.',
    price: 5900,
    image: null,
  },
  {
    id: 'mousse-chocolate',
    category: 'postres',
    name: 'Mousse de Chocolate',
    description: 'Mousse de chocolate artesanal, suave y cremosa.',
    price: 5900,
    image: null,
  },
  {
    id: 'lemon-pie',
    category: 'postres',
    name: 'Lemon Pie',
    description: 'Clásico lemon pie casero con merengue a punto.',
    price: 5900,
    image: null,
  },

  // ---- BEBIDAS ----
  {
    id: 'coca-cola',
    category: 'bebidas',
    name: 'Gaseosa Línea Coca',
    description: 'Coca Cola, Sprite o Fanta. Bien fría!',
    price: 3500,
    image: null,
  },
  {
    id: 'pepsi',
    category: 'bebidas',
    name: 'Gaseosa Línea Pepsi',
    description: 'Pepsi, 7Up o Mirinda.',
    price: 3200,
    image: null,
  },
  {
    id: 'aguas-saborizadas',
    category: 'bebidas',
    name: 'Aguas Saborizadas',
    description: 'Agua saborizada natural.',
    price: 3000,
    image: null,
  },
  {
    id: 'agua-mineral',
    category: 'bebidas',
    name: 'Agua Mineral',
    description: 'Agua mineral con o sin gas.',
    price: 3000,
    image: null,
  },
  {
    id: 'limonada',
    category: 'bebidas',
    name: 'Limonada Natural',
    description: 'Limonada natural bien fresca.',
    price: 2500,
    image: null,
  },

  // ---- TRAGOS ----
  {
    id: 'gin-tonic',
    category: 'tragos',
    name: 'Gin Tonic',
    description: 'Gin tonic clásico con tónica y rodaja de limón.',
    price: 7500,
    image: null,
  },
  {
    id: 'campari',
    category: 'tragos',
    name: 'Campari con Naranja',
    description: 'Campari con jugo de naranja natural y hielo.',
    price: 7500,
    image: null,
  },
  {
    id: 'cerveza-artesanal',
    category: 'tragos',
    name: 'Cerveza Artesanal',
    description: 'Cerveza artesanal tirada, rubia o roja.',
    price: 5500,
    image: null,
  },
  {
    id: 'ipa',
    category: 'tragos',
    name: 'IPA',
    description: 'Indian Pale Ale artesanal, amarga y aromática.',
    price: 6900,
    image: null,
    badge: 'Premium',
  },

  // ---- CERVEZAS ----
  {
    id: 'heineken',
    category: 'cervezas',
    name: 'Heineken',
    description: 'Cerveza Heineken en lata o porrón.',
    price: 5500,
    image: null,
  },
  {
    id: 'corona',
    category: 'cervezas',
    name: 'Corona',
    description: 'Cerveza Corona en lata o porrón.',
    price: 5500,
    image: null,
  },
  {
    id: 'stella',
    category: 'cervezas',
    name: 'Stella Artois',
    description: 'Cerveza Stella Artois en lata o porrón.',
    price: 5500,
    image: null,
  },
  {
    id: 'strauss',
    category: 'cervezas',
    name: 'Strauss Sin TACC',
    description: 'Cerveza Strauss libre de gluten.',
    price: 5500,
    image: null,
    badge: 'Sin TACC',
  },
]

export function formatCurrency(value) {
  return new Intl.NumberFormat('es-AR', {
    style: 'currency',
    currency: 'ARS',
    maximumFractionDigits: 0,
  }).format(value)
}
